// km95api.h Keyman 5 structures and functions

#ifndef _KM95API_H
#define _KM95API_H

#ifdef __cplusplus
extern "C" {
#endif

#define KM_DISABLEUI	1
#define KM_ENABLEUI	2

#define RWM_KMKBCHANGE    "WM_KMKBCHANGE"
#define RWM_KMSELECTLANG  "WM_KMSELECTLANG"
#define RWM_KMMESSAGE     "WM_KMMESSAGE"
#define RWM_KEYMAN	"WM_KEYMAN"

#define KEYMANID_IGNORE		0xFFFFFFFE
#define KEYMANID_NONKEYMAN	0xFFFFFFFF

typedef enum TSelectKeyboardType {skHKL, skKeymanID, skActiveHKL} SelectKeyboardType;

#define LPSTORE LPVOID // AB Temp fix
#define LPGROUP LPVOID // AB Temp fix

typedef struct tagKEYBOARD
{
	DWORD dwIdentifier;	// Keyman compiled keyboard id
	DWORD dwFileVersion;	// Version of the file - Keyman 5.0.105.0+ is 0x0501
	DWORD dwCheckSum;		// As stored in keyboard file
	DWORD xxkbdlayout;     	// obsolete
	DWORD IsRegistered;	// Was the keyboard created with a registered version
	DWORD version;		// keyboard version
	DWORD cxStoreArray;	// in array entries
	DWORD cxGroupArray;	// in array entries

	LPSTORE dpStoreArray;	// [LPSTORE] address of first item in store array
	LPGROUP dpGroupArray;	// [LPGROUP] address of first item in group array
	
	DWORD StartGroup[2];	// index of starting groups [2 of them]
				// Ansi=0, Unicode=1

	DWORD dwFlags;		// Flags for the keyboard file

	DWORD dwHotKey;		// default kbd hotkey (hiword=shift/ctrl/alt stuff, loword=vkey)

	HBITMAP	hBitmap;		// handle to the bitmap in the file;
} KEYBOARD, *LPKEYBOARD;

typedef BOOL (WINAPI *IMDLLHOOKProc)(HWND hwndFocus, WORD KeyStroke, WCHAR KeyChar, DWORD shiftFlags);

typedef struct tagIMDLLHOOK
{
	char name[32];		// Function name in IMX	
DWORD storeno;		// Associated store number in tagKEYBOARD
	IMDLLHOOKProc function;	// pointer to DLL hook function
} IMDLLHOOK, *LPIMDLLHOOK;
	
typedef struct tagIMDLL
{
	char        Filename[256]; // Filename of DLL, no path information
	HMODULE     hModule;      // Handle to in-memory module
	DWORD       nHooks;       // Number of hooks associated with IMX DLL
	LPIMDLLHOOK Hooks;        // Pointer to IMX hook information structures
} IMDLL, *LPIMDLL;

typedef struct tagKEYBOARDINFO
{
	DWORD      KeymanID;	// Generated by Keyman, as per registry
	DWORD      HotKey;	// User selected hotkey for keyboard
	DWORD      KeyboardID;	// Associated system shadow layout ID
	char       Name[256];	// Keyboard name, e.g. imyi for imyi.kmx
	LPKEYBOARD Keyboard;	// Pointer to tagKEYBOARD structure
	DWORD      nIMDLLs;	// Number of IMX DLLs associated with keyboard
	LPIMDLL    IMDLLs;	// Pointer to IMX DLL information structures
} KEYBOARDINFO, *LPKEYBOARDINFO;

BOOL WINAPI Keyman_BuildKeyboardList(LPKEYBOARDINFO kbd, int *n);
BOOL WINAPI Keyman_ForceKeyboard(PCSTR FileName);
BOOL WINAPI Keyman_StopForcingKeyboard();

#ifdef Deprecated
// following functions and structures are deprecated; use instead structures and 
// functions listed above
typedef struct tagKEYMANKEYBOARDINFO {
	DWORD	cbSize;
	DWORD	KeymanID;
	DWORD	layout;
	char	szName[80];
	char	szFileName[256];
	char	szMessage[1024];
	char	szCopyright[256];
	HBITMAP hBitmap;
	int	bcx, bcy;
	DWORD	hotkey;
	} KEYMANKEYBOARDINFO, FAR *LPKEYMANKEYBOARDINFO;

typedef struct tagKEYMANINFO {
	DWORD cbSize;
	} KEYMANINFO, FAR *LPKEYMANINFO;

BOOL WINAPI GetKeymanKeyboardInfo(LPKEYMANKEYBOARDINFO kki);
BOOL WINAPI GetKeymanInfo(LPKEYMANINFO ki);
#endif

#ifdef __cplusplus
}	// extern "C"
#endif 

#endif	// _KM95API_H

